spring.application.name=ForkAvito
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/Ads-onlineDB
spring.datasource.username=Ads
spring.datasource.password=Ads
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.show-sql=true

jwt.secret=+69CYjMhk9v3VtMcznIX6PQIgXQ/+Ivxlnz1Qo/8Xsc=
jwt.expiration=15m

frontend.url:http://localhost:3000

spring.datasource.H2.url=jdbc:h2:mem:testdb
spring.datasource.H2.driver=org.h2.Driver
spring.datasource.H2.username=sa
spring.datasource.H2.password=
