spring.application.name=ForkAvito
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

frontend.url=http://localhost:3000

path.to.users.image.folder=/users/images
path.to.ads.image.folder=/ads/images
path.to.parent.folder=D:\\SkyPro\\Diplom