spring.application.name=ForkAvito
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=jdbc:postgresql://localhost:5432/Ads-onlineDB
spring.datasource.username=Ads
spring.datasource.password=Ads
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.show-sql=true