--liquibase formatted sql

--changeset isolomin:1
CREATE TABLE if NOT EXISTS users (
    id INTEGER generated by default as identity primary key,
    username CHARACTER VARYING(255) UNIQUE not null,
    password CHARACTER VARYING(255) not null,
    first_name CHARACTER VARYING(255) not null,
    last_name CHARACTER VARYING(255) not null,
    phone CHARACTER VARYING(255) not null,
    role CHARACTER VARYING(255) not null,
    image CHARACTER VARYING(255)
);

CREATE TABLE if NOT EXISTS ads (
    pk INTEGER generated by default as identity primary key,
    author INTEGER not null,
    image CHARACTER VARYING(255) not null,
    price INTEGER not null,
    title CHARACTER VARYING(255) not null,
    description CHARACTER VARYING(255) not null,
    user_id INTEGER REFERENCES users (id) not null,
    comment_id INTEGER REFERENCES users (id)
);

CREATE TABLE if NOT EXISTS comments (
    pk INTEGER generated by default as identity primary key,
    author INTEGER not null,
    author_image CHARACTER VARYING(255) not null,
    author_first_name CHARACTER VARYING(255) not null,
    created_at BIGINT not null,
    text CHARACTER VARYING(255) not null,
    user_id INTEGER REFERENCES users (id) not null,
    ad_id INTEGER REFERENCES ads (pk) not null
);